authapp/urls.py
from authapp.apps import AuthappConfig
from django.urls import path
from authapp.views import CustomLoginView, RegisterView, CustomLogoutView, EditView

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('edit/', EditView.as_view(), name='edit')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('courses/', views.CoursesListView.as_view(), name='courses'),
    path('courses/<int:pk>/', views.CoursesDetailView.as_view(), name="courses_detail"),
    path('docsite/', views.DocSiteView.as_view(), name='docsite'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('news/', views.NewsView.as_view(), name='news'),
    path('news/<int:pk>/', views.NewsDetailView.as_view(), name='news_detail'),
    path('news/<int:page>/', views.NewsWithPaginatorView.as_view(), name='news_paginator'),
]

mainapp/models.py
from django.db import models
from django.db.models.query import QuerySet

NULLABLE = {'blank': True, 'null': True}


class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited")
    deleted = models.BooleanField(default=False, verbose_name="Deleted")

    class Meta:
        abstract = True
        ordering = ['-created']

    def delete(self, *args, **kwargs):
        self.deleted = True
        self.save()

    def live(self):
        self.deleted = False
        self.save()

    def hard_delete(self):
        super(BaseModel, self).delete()


class BaseQuerySet(QuerySet):

    def delete(self, *args, **kwargs):
        return super(BaseQuerySet, self).update(deleted=True)

    def hard_delete(self):
        return super(BaseQuerySet, self).delete()


class NewsManager(models.Manager):

    def get_queryset(self):
        return BaseQuerySet(self.model).filter(deleted=False)


class News(BaseModel):

    objects = NewsManager()
    all_objects = models.Manager()

    title = models.CharField(max_length=256, verbose_name="Title")
    preamble = models.CharField(max_length=1024, verbose_name="Preamble")
    body = models.TextField(verbose_name="Body", **NULLABLE)
    body_as_markdown = models.BooleanField(default=False, verbose_name="As markdown")

    def __str__(self):
        return f'#{self.pk} {self.title}'

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'


class Course(BaseModel):
    name = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", **NULLABLE)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Cost", default=0)
    cover = models.CharField(max_length=25, default="no_image.svg", verbose_name="Cover")

    def __str__(self):
        return f"{self.pk} {self.name}"

    class Meta:
        verbose_name = 'курс'
        verbose_name_plural = 'курсы'


class Lesson(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Lesson number")
    title = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", **NULLABLE)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)

    def __str__(self):
        return f"{self.course.name} | {self.num} | {self.title}"

    class Meta:
        verbose_name = 'урок'
        verbose_name_plural = 'уроки'
        ordering = ("course", "num")


class CoursesTeacher(BaseModel):
    courses = models.ManyToManyField(Course)
    name_first = models.CharField(max_length=128, verbose_name="Name")
    name_second = models.CharField(max_length=128, verbose_name="Surname")
    day_birth = models.DateField(verbose_name="Birth date")
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return "{0:0>3} {1} {2}".format(self.pk, self.name_second, self.name_first)

mainapp/views.py
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404

from mainapp.models import *


class ContactsView(TemplateView):
    template_name = 'mainapp/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contacts'] = [
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHcrhA',
                'city': 'Санкт‑Петербург',
                'phone': '+7-999-11-11111',
                'email': 'geeklab@spb.ru',
                'adds': 'территория Петропавловская крепость, 3Ж',
            }, {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHX3xB',
                'city': 'Казань',
                'phone': '+7-999-22-22222',
                'email': 'geeklab@kz.ru',
                'adds': 'территория Кремль, 11, Казань, Республика Татарстан, Россия',
            }, {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHh9kD',
                'city': 'Москва',
                'phone': '+7-999-33-33333',
                'email': 'geeklab@msk.ru',
                'adds': 'Красная площадь, 7, Москва, Россия',
            },
        ]
        return context


class CoursesListView(TemplateView):
    template_name = 'mainapp/courses_list.html'

    def get_context_data(self, **kwargs):
        context = super(CoursesListView, self).get_context_data(**kwargs)
        context['objects'] = Course.objects.all()[:7]
        return context


class CoursesDetailView(TemplateView):
    template_name = 'mainapp/courses_detail.html'

    def get_context_data(self, pk=None, **kwargs):
        context = super(CoursesDetailView, self).get_context_data(**kwargs)
        context['course_object'] = get_object_or_404(Course, pk=pk)
        context['lessons'] = Lesson.objects.filter(course=context['course_object'])
        context['teachers'] = CoursesTeacher.objects.filter(courses=context['course_object'])
        return context


class DocSiteView(TemplateView):
    template_name = 'mainapp/doc_site.html'


class IndexView(TemplateView):
    template_name = 'mainapp/index.html'


class LoginView(TemplateView):
    template_name = 'mainapp/login.html'


class NewsView(TemplateView):
    template_name = 'mainapp/news.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = News.objects.all()[:5]
        return context


class NewsDetailView(TemplateView):
    template_name = "mainapp/news_detail.html"

    def get_context_data(self, pk=None, **kwargs):
        context = super().get_context_data(pk=pk, **kwargs)
        context['news_object'] = get_object_or_404(News, pk=pk)
        return context


class NewsWithPaginatorView(NewsView):

    def get_context_data(self, page, **kwargs):
        context = super().get_context_data(page=page, **kwargs)
        context['page_num'] = page
        return context

mainapp/templates/mainapp/includes/inc_main_menu.html
{% with request.resolver_match.view_name as view_name %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {%  if view_name == 'mainapp:news' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'mainapp:news' %}">Новости</a>
                    </li>
                    <li class="nav-item {% if view_name == 'mainapp:courses' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'mainapp:courses' %}">Курсы</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Профиль
                        </a>
                        <div class="dropdown-menu" aria-labelledby="ddProfile">
                            <a class="dropdown-item" href="#">Редактировать профиль</a>
                            <a class="dropdown-item" href="#">Мои курсы</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Модерация</a>
                            <a class="dropdown-item" href="#">Административный раздел</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Выход</a>
                        </div>
                    </li>
                    <li class="nav-item {% if view_name == 'mainapp:contacts' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'mainapp:contacts' %}">Контакты</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item" >
                        <a class="nav-link" href="{% url 'authapp:edit' %}">
                            {{ user.first_name|default:user.username }}
                        </a>
                    </li>
                    <li class="nav-item" >
                        <a class="nav-link" href="{% url 'authapp:logout' %}">Выйти</a>
                    </li>
                    {% else %}
                    <li class="nav-item" >
                        <a class="nav-link" href="{% url 'authapp:login' %}">Войти</a>
                    </li>
                    {% endif %}
                </ul>
                <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a href="#">🇬🇧</a></span>
            </div>
{% endwith %}