config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('courses/', views.CoursesListView.as_view(), name='courses'),
    path('courses/<int:pk>/', views.CoursesDetailView.as_view(), name="courses_detail"),
    path('docsite/', views.DocSiteView.as_view(), name='docsite'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('news/', views.NewsView.as_view(), name='news'),
    path('news/<int:pk>/', views.NewsDetailView.as_view(), name='news_detail'),
    path('news/<int:page>/', views.NewsWithPaginatorView.as_view(), name='news_paginator'),
]

mainapp/models.py
from django.db import models
from django.db.models.query import QuerySet

NULLABLE = {'blank': True, 'null': True}


class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited")
    deleted = models.BooleanField(default=False, verbose_name="Deleted")

    class Meta:
        abstract = True
        ordering = ['-created']

    def delete(self, *args, **kwargs):
        self.deleted = True
        self.save()

    def live(self):
        self.deleted = False
        self.save()

    def hard_delete(self):
        super(BaseModel, self).delete()


class BaseQuerySet(QuerySet):

    def delete(self, *args, **kwargs):
        return super(BaseQuerySet, self).update(deleted=True)

    def hard_delete(self):
        return super(BaseQuerySet, self).delete()


class NewsManager(models.Manager):

    def get_queryset(self):
        return BaseQuerySet(self.model).filter(deleted=False)


class News(BaseModel):

    objects = NewsManager()
    all_objects = models.Manager()

    title = models.CharField(max_length=256, verbose_name="Title")
    preamble = models.CharField(max_length=1024, verbose_name="Preamble")
    body = models.TextField(verbose_name="Body", **NULLABLE)
    body_as_markdown = models.BooleanField(default=False, verbose_name="As markdown")

    def __str__(self):
        return f'#{self.pk} {self.title}'

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'


class Course(BaseModel):
    name = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", **NULLABLE)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Cost", default=0)
    cover = models.CharField(max_length=25, default="no_image.svg", verbose_name="Cover")

    def __str__(self):
        return f"{self.pk} {self.name}"

    class Meta:
        verbose_name = 'курс'
        verbose_name_plural = 'курсы'


class Lesson(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Lesson number")
    title = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", **NULLABLE)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)

    def __str__(self):
        return f"{self.course.name} | {self.num} | {self.title}"

    class Meta:
        verbose_name = 'урок'
        verbose_name_plural = 'уроки'
        ordering = ("course", "num")


class CoursesTeacher(BaseModel):
    courses = models.ManyToManyField(Course)
    name_first = models.CharField(max_length=128, verbose_name="Name")
    name_second = models.CharField(max_length=128, verbose_name="Surname")
    day_birth = models.DateField(verbose_name="Birth date")
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return "{0:0>3} {1} {2}".format(self.pk, self.name_second, self.name_first)

mainapp/views.py
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404

from mainapp.models import *


class ContactsView(TemplateView):
    template_name = 'mainapp/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contacts'] = [
            {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHcrhA',
                'city': 'Санкт‑Петербург',
                'phone': '+7-999-11-11111',
                'email': 'geeklab@spb.ru',
                'adds': 'территория Петропавловская крепость, 3Ж',
            }, {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHX3xB',
                'city': 'Казань',
                'phone': '+7-999-22-22222',
                'email': 'geeklab@kz.ru',
                'adds': 'территория Кремль, 11, Казань, Республика Татарстан, Россия',
            }, {
                'map': 'https://yandex.ru/map-widget/v1/-/CCUAZHh9kD',
                'city': 'Москва',
                'phone': '+7-999-33-33333',
                'email': 'geeklab@msk.ru',
                'adds': 'Красная площадь, 7, Москва, Россия',
            },
        ]
        return context


class CoursesListView(TemplateView):
    template_name = 'mainapp/courses_list.html'

    def get_context_data(self, **kwargs):
        context = super(CoursesListView, self).get_context_data(**kwargs)
        context['objects'] = Course.objects.all()[:7]
        return context


class CoursesDetailView(TemplateView):
    template_name = 'mainapp/courses_detail.html'

    def get_context_data(self, pk=None, **kwargs):
        context = super(CoursesDetailView, self).get_context_data(**kwargs)
        context['course_object'] = get_object_or_404(Course, pk=pk)
        context['lessons'] = Lesson.objects.filter(course=context['course_object'])
        context['teachers'] = CoursesTeacher.objects.filter(courses=context['course_object'])
        return context


class DocSiteView(TemplateView):
    template_name = 'mainapp/doc_site.html'


class IndexView(TemplateView):
    template_name = 'mainapp/index.html'


class LoginView(TemplateView):
    template_name = 'mainapp/login.html'


class NewsView(TemplateView):
    template_name = 'mainapp/news.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = News.objects.all()[:5]
        return context


class NewsDetailView(TemplateView):
    template_name = "mainapp/news_detail.html"

    def get_context_data(self, pk=None, **kwargs):
        context = super().get_context_data(pk=pk, **kwargs)
        context['news_object'] = get_object_or_404(News, pk=pk)
        return context


class NewsWithPaginatorView(NewsView):

    def get_context_data(self, page, **kwargs):
        context = super().get_context_data(page=page, **kwargs)
        context['page_num'] = page
        return context

mainapp/templates/mainapp/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

    <title>
        {% block title %}
            Welcome to Braniac!
        {% endblock title %}
    </title>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'mainapp:index' %}">
            <img src="{% static 'img/logo.png' %}" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        {% include 'mainapp/includes/inc_main_menu.html' %}

    </div>
</nav>


<div class="container-md">
    {% block content %}
    {% endblock %}
</div>


<!-- Footer -->

<div class="container-lg mt-auto">
    <hr>
    <div class="row justify-content-center">
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Braniac</strong>
            </p>
            <p>
            <ul class="list-unstyled">
                <li><a href="{% url 'mainapp:index' %}">Домашняя</a></li>
                <li><a href="{% url 'mainapp:news' %}">Новости</a></li>
                <li><a href="{% url 'mainapp:login' %}">Войти</a></li>
            </ul>
            </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Полезное</strong>
            </p>
            <p>
            <ul class="list-unstyled">
                <li><a href="#">Положения &amp; Условия</a></li>
                <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
                <li><a href="#">Документация по API</a></li>
                <li><a href="{% url 'mainapp:docsite' %}">Документация по сайту</a></li>
            </ul>
            </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Мы в социальных сетях</strong>
            </p>
            <p>
            <div class="row justify-content-around">
                <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
            </div>
            </p>
            <p>
                <strong>Наше приложение</strong>
            </p>
            <p>
            <div class="row justify-content-around">
                <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-windows fa-2x"></i></a></div>
            </div>
            </p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div>
            <p><small>&copy; GeekBrains 2021</small></p>
        </div>
    </div>
</div>

<!-- /Footer -->


<!-- JavaScript section -->
<!-- Bootstrap -->
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- ChartJs -->
<script src="{% static 'js/Chart.min.js' %}"></script>

<!-- FontAwesome -->
<script src="{% static 'js/fontawesome.all.min.js' %}"></script>


</body>

</html>

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load email_to_link %}
{% block content %}
    <p>
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Наши контакты</h1>
            <p class="lead">Обязательно свяжитесь с нами! Ваш комфорт - наша забота.</p>
        </div>
    </div>
    </p>
    <p>
    <div class="row justify-content-around mt-n2">



    {% for contact in contacts %}
        <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
            <div class="card h-100 shadow">
                <div class="card-body">
                    <div style="position:relative;overflow:hidden;">
                        <iframe src="{{ contact.map }}" width="100%" height="300"
                                frameborder="0" allowfullscreen="true"
                                style="position:relative; border-radius: 4px;"></iframe>
                    </div>
                    <h5 class="card-title">{{ contact.city }}</h5>
                    <p class="card-text">
                    <ul class="list-unstyled">
                        <li>Телефон</li>
                        <li><strong>{{ contact.phone }}</strong></li>
                    </ul>
                    <ul class="list-unstyled">
                        <li>Email</li>
                        <li><strong>{{ contact.email|email_to_link }}</strong></li>
                    </ul>
                    <ul class="list-unstyled">
                        <li>Адрес</li>
                        <li><strong>{{ contact.adds }}</strong></li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
{% endfor %}

    </div>
    </p>
{% endblock %}

mainapp/templates/mainapp/courses_detail.html
{% extends 'mainapp/base.html' %}
{% load static markdownify %}
{% load static %}

{% block title %}
    {{ course_object.name }}
{% endblock title %}


{% block content %}
    <h1 class="mt-2">
        {{ course_object.name }}
    </h1>
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-6 col-lg-8 order-2 order-md-1">
            <div class="row h-100">
                <div class="col-12">
                    {% if course_object.description_as_markdown %}
                        {{ course_object.description|markdownify }}
                    {% else %}
                        {{ course_object.description }}
                    {% endif %}
                </div>
                <div class="col-12 align-self-end">
                    <p>
                        <small>Преподаватели</small><br>
                        {% for item in teachers %}
                            {{ item.name_second }} {{ item.name_first }};
                        {% endfor %}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4 order-1 order-md-2">
            <div class="row h-100">
                <div class="col-12 align-self-start">
                    <img class="w-100" src="{% static course_object.cover %}" alt="#">
                </div>
                <div class="col-12 align-self-end d-none d-md-block">
                    <p class="text-center mt-2">
                        <small class="text-uppercase">цена</small><br>
                        <span style="font-size: 30pt;">{{ course_object.cost }}</span><br>
                        <a href="#" class="btn btn-outline-primary btn-block"
                           role="button">Купить</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 d-md-none order-3 order-sm-3">
            <p class="text-center">
                <small class="text-uppercase">цена</small><br>
                <span style="font-size: 30pt;">{{ course_object.cost }}</span><br>
                <a href="#" class="btn btn-outline-primary btn-block"
                   role="button">Купить</a>
            </p>
        </div>
    </div>
    <div class="accordion" id="accordionLessons">
        {% for item in lessons %}
            <div class="card">
                <div class="card-header" id="headLessonPk{{ item.pk }}">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left" type="button"
                                data-toggle="collapse" data-target="#collapse{{ item.pk }}"
                                aria-expanded="true" aria-controls="collapse{{ item.pk }}">
                            {{ item.course.name }} - {{ item.title }}
                        </button>
                    </h2>
                </div>
                <div id="collapse{{ item.pk }}" class="collapse"
                     aria-labelledby="headLessonPk{{ item.pk }}"
                     data-parent="#accordionLessons">
                    <div class="card-body">
                        <div class="row justify-content-center">
                            <div class="col-12 text-center">
                                <img src="{% static 'img/no_image.svg' %}"
                                     width="150px" alt="#">
                            </div>
                            <div class="col-12">
                                {% if item.description_as_markdown %}
                                    {{ item.description|markdownify }}
                                {% else %}
                                    {{ item.description }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

mainapp/templates/mainapp/courses_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}
    Курсы
{% endblock title %}

{% block content %}

    <div class="row justify-content-center mt-3">

    {% for course_item in objects %}
        <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
            <a href="{% url 'mainapp:courses_detail' pk=course_item.pk %}">
                <img src="{% static course_item.cover %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title text-center">{{ course_item.name }}</h5>
                </div>
            </a>
        </div>
    {% endfor %}


    </div>
    <div class="row justify-content-center align-items-center mt-3 mb-n3">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
            </ul>
        </nav>
    </div>
{% endblock %}

mainapp/templates/mainapp/doc_site.html
{% extends 'mainapp/base.html' %}
{% block content %}

    <div class="row justify-content-center align-items-center mt-3">
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    Документация по сайту
                </div>
                <div class="card-body">

                    <h5 class="card-title">CSS-стили</h5>
                    <p class="card-text">
                    <ul>
                        <li><a href="https://getbootstrap.com/docs/4.6/getting-started/introduction/" target="_blank">Bootstrap
                            v4.6</a></li>
                        <li><a href="https://bootswatch.com/lumen/" target="_blank">Bootstrap theme: Lumen</a></li>
                    </ul>
                    </p>

                    <h5 class="card-title">Иконки</h5>
                    <p class="card-text">
                        <a href="https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use">FontAwesome
                            5.15.3</a>
                    </p>

                    <h5 class="card-title">Графики</h5>
                    <p class="card-text">
                        <a href="https://www.chartjs.org/">ChartJS</a>
                    </p>

                    <h5 class="card-title">Графика</h5>
                    <p class="card-text">
                    <ul>
                        <li><a href="https://www5.flamingtext.com/" target="_blank" rel="noopener noreferrer">Логотип by
                            flamingtext.com</a></li>
                        <li><a href="https://www.pexels.com/ru-ru" target="_blank" rel="noopener noreferrer">Фотографии
                            by
                            pexels.com</a>. Все изображения распространяются под бесплатной лицензией. Для страницы
                            обзоров фотографии
                            должны быть с соотношением сторон кратным 2.912 (например, 1920x659)
                        </li>
                        <li><a href="https://getavataaars.com/" target="_blank" rel="noopener noreferrer">Аватарки
                            пользователей by
                            getavataaars.com</a></li>
                    </ul>
                    </p>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/login.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

    <title>Welcome to GeekLab!</title>
</head>

<body>





<div class="row justify-content-around align-items-center" style="height: 100vh; margin: 0px">
  <div class="text-center">
    <p>
      <a href="{% url 'mainapp:index' %}"><img src="/static/img/logo.png" alt=""></a>
    </p>
    <h2>Вход пользователя</h2>
    <form>
      <p>
        <input id="id_username" class="form-control" type="text" name="username" placeholder="Имя пользователя"
          required="" autofocus="">
      </p>
      <p>
        <input id="id_password" class="form-control" type="password" name="password" placeholder="Пароль" required="">
      </p>
      <p>
        <button type="submit" class="btn btn-primary btn-block">Войти</button>
      </p>
    </form>
    <p class="text-right">
      <a href=""><small>Забыли пароль?</small></a>
    </p>
    <h4>Вход через социальные сети</h4>
    <p>
    <div class="btn-group btn-block" role="group">
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-vk"></i></a>
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-github"></i></a>
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-facebook"></i></a>
    </div>
    </p>
  </div>
</div>








    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="/static/js/jquery-3.6.0.min.js"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

    <!-- ChartJs -->
    <script src="/static/js/Chart.min.js"></script>

    <!-- FontAwesome -->
    <script src="/static/js/fontawesome.all.min.js"></script>



</body>

</html>

mainapp/templates/mainapp/news.html
{% extends 'mainapp/base.html' %}

{% block title %}
    Новости
{% endblock title %}

{% block content %}
    {% with range as range %}

        <div class="row">

            <div class="col-lg-8">
                {% for news_item in object_list %}
                    <div class="card my-2">
                        <div class="card-body">
                            <h5 class="card-title">{{ news_item.title }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ news_item.created|date:'d.m.Y' }}</h6>
                            <p class="card-text">{{ news_item.preamble }}</p>
                            <a href="{% url 'mainapp:news_detail' pk=news_item.pk %}" class="card-link">Подробнее</a>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="col-lg-4">
                <div class="card my-2 sticky-top">
                    <div class="card-header">
                        Фильтры
                    </div>
                    <div class="card-body">
                        <form action="">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">Дата от...</span>
                                </div>
                                <input type="date" class="form-control" name="dateFrom">
                            </div>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">Дата до...</span>
                                </div>
                                <input type="date" class="form-control" name="dateTo">
                            </div>

                            <button type="submit" class="btn btn-primary btn-block">Фильтровать</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>

        <div class="row justify-content-center align-items-center mt-3 mb-n3">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                    <li class="page-item"><a class="page-link" href="{% url 'mainapp:news_paginator' 1 %}">1</a></li>
                    <li class="page-item"><a class="page-link" href="{% url 'mainapp:news_paginator' page=2 %}">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">Next</a></li>
                </ul>
            </nav>
        </div>

    {% endwith %}
{% endblock %}

mainapp/templates/mainapp/news_detail.html
{% extends 'mainapp/base.html' %}

{% block title %}
{{ news_object.title|default:"Новости" }}
{% endblock title %}

{% block content %}

    <div class="row justify-content-center pt-3">
        <div class="col-md-12 col-lg-8">
            <div class="card shadow">
                <div class="card-body">
                    <h5 class="card-title">{{ news_object.title }}</h5>
                    <p class="card-text">
                        {{ news_object.body }}
                    </p>
                    <a href="{% url 'mainapp:news' %}"
                       class="btn btn-primary">Назад</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}